# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0080875e31fc00c1c43577431add9c4eb101697b73b4b4aaa93ca58f92fdfa611344a2348ace5390446df0a23f5b30e4f2add63b17b944f33906fe2a68ee8691

test:
  secret_key_base: 91b75e3734c28124460eb3335cb820d62c044c5e1248a1869b2fa59fc65c1ad7fbce9e56fb6a8479e9534fdb5c9559a72a20cfbb5119323fe77144721c1f70c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
